# Exercise 4.1: First steps with ```numpy```

Generate the following sequences/ vectors/ matrices without using loops:

**a)** $\bigl(\sin(\pi n)\bigr)_{n=1,\dots,12}$ and $\bigl( \frac{1}{1+n^2} \bigr)_{n=1,\dots,12}$

In [1]:
# write your code here

import numpy as np

seq_1 = np.sin(np.pi * np.arange(1,13))
seq_2 = 1/ (1+ np.arange(1,13)**2)

In [2]:
seq_1

array([ 1.22464680e-16, -2.44929360e-16,  3.67394040e-16, -4.89858720e-16,
        6.12323400e-16, -7.34788079e-16,  8.57252759e-16, -9.79717439e-16,
        1.10218212e-15, -1.22464680e-15,  4.89982516e-15, -1.46957616e-15])

In [3]:
seq_2

array([0.5       , 0.2       , 0.1       , 0.05882353, 0.03846154,
       0.02702703, 0.02      , 0.01538462, 0.01219512, 0.00990099,
       0.00819672, 0.00689655])

**b)** $(1,-3,5,-7,9,\dots,97,-99)$

In [4]:
# write your code here

vec = np.arange(1,100,2)
vec[1::2] = -vec[1::2]

vec

array([  1,  -3,   5,  -7,   9, -11,  13, -15,  17, -19,  21, -23,  25,
       -27,  29, -31,  33, -35,  37, -39,  41, -43,  45, -47,  49, -51,
        53, -55,  57, -59,  61, -63,  65, -67,  69, -71,  73, -75,  77,
       -79,  81, -83,  85, -87,  89, -91,  93, -95,  97, -99])

**c)** $\begin{pmatrix}
    1/z & 1 & 1 & \dots & 1\\
    z & 1/z & z & \dots & z\\
    \vdots & & & \ddots & \\
    z^{11} & z^{11} & z^{11} & \dots & 1/z
    \end{pmatrix}$, where $z=\frac{\sqrt{3}+i}{2}$ and $i$ is the imaginary unit.

In [6]:
# write your code here

# We first generate a matrix of degrees of z in the disired matrix

n = 12 # size of the matrix

# construct a matrix with number i in all the values of row i
mat = np.arange(n).repeat(n).reshape((n,n))

# numpy.repeat function repeats elements of an array a given number of times,
# e.g. numpy.repeat([1,2,3],2)  = [1,1,2,2,3,3]

# replace all the diagonal values of the matrix with -1
mat[(np.arange(n), np.arange(n))] = np.array([-1]*n)


mat

array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2, -1,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3, -1,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4, -1,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5, -1,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6, -1,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7, -1,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8, -1,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9, -1,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, -1, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1]])

In [7]:
z = (np.sqrt(3)+ 1j)/ 2 # 1j is the imaginary unit in Python

# Now we get the desired matrix as z**mat
mat = z**mat

# Exercise 4.2: Least squares

The ordinary least squares problem with matrix of observations $X\in\mathbb{R}^{N\times p}$ and vector of responses $y\in\mathbb{R}^N$ is given by 

$$\min_{w\in\mathbb{R}^p} \|Xw-y\|_2^2$$
 
and has a well-known analytical solution (assuming that $X$ has full column rank):

$$w^* = (X^TX)^{-1}X^T y$$

Write a function that takes $X$ and $y$ as input and returns the solution of the ordinary least squares problem. Generate a random Gaussian matrix $X$ and vector $y$ (such that $N>p$, so that $X$ almost surely has a full column rank) and check if your function returns the right solution on these inputs (i.e. if it holds that $Xw^*-y=0$ up to a small constant $\epsilon$).

In [7]:
# write your code here

def OLS(X,y):
    return np.linalg.inv(X.T@X)@X.T@y # np.linalg.inv computes the inverse of a matrix

In [8]:
N = 100
p = 10

X = np.random.normal(size=(N,N))
y = np.random.normal(size=(N,1))

w = OLS(X,y)


np.linalg.norm(X@w - y)

1.8501280851621286e-09

# Exercise 4.3: The shortest mathematical paper

A [candidate for the shortest mathematical paper ever](https://www.ams.org/journals/bull/1966-72-06/S0002-9904-1966-11654-3/S0002-9904-1966-11654-3.pdf) shows the following result:

$$27^5+84^5+110^5+133^5=144^5$$

This is a counterexample to the [Euler's sum of powers conjecture](https://en.wikipedia.org/wiki/Euler%27s_sum_of_powers_conjecture), which states that if the sum of $n$ many $k-$th powers of positive integers is itself a $k-$th power, then $n\geq k$.

**a)** Check if the equation above is true.

In [9]:
# write your code here

# We check the statement by simple calculation

27**5 + 84**5 + 110**5 + 133**5 == 144**5 

True

**b)** The more interesting statement in the paper is that the equation above gives the smallest counterexample, i.e. for any five integers smaller than $144$ denoted $a,b,c,d$ and $e$, it does not hold that $a^5+b^5+c^5+d^5=e^5$. Check this statement using Python. 

Notice that the number of all the possible combinations of four integers $a,b,c,d$ smaller than $N$ grows very quickly with $N$:
 
$$\binom{N}{4} = \frac{N(N-1)(N-2)(N-3)}{24} = O(N^4)$$

In particular, there are around 17 million combinations for $N=144$. Therefore, you need to mind efficiency and memory issues while doing this task. You can follow the following algorithm:

 1. Construct a ```numpy``` array of integers from 1 to 144 to the fifth power.
 2. Construct a list (or an array) of all combinations of four elements from this array. You can use ```combinations``` function from ```itertools``` package for this.
 3. Construct a list (or an array) of sums of all these combinations.
 4. Loop over one list and check if the entry appears in the other list (i.e., use the ```in``` keyword).

The last loop may take some time. Can you come up with a more efficient solution?

In [10]:
# write your code here

from itertools import combinations

nums = np.arange(1,145,1)**5
combs = np.array(list(combinations(nums, 4)))

sums = combs.sum(axis=1)

for s, c in zip(sums,combs):
    if s in nums:
        print(f"Integers {[int(i**(1/5)) for i in c]} in fifth degree sum to {int(s**(1/5))}^5.")  

Integers [27, 84, 110, 133] in fifth degree sum to 144^5.


In [11]:
# We can also use numpy to avoid the long loops and thus check the statement much faster

intersection = np.in1d(sums, nums)

for i in np.argwhere(intersection==True).ravel():
    print(f"Integers {[int(i**(1/5)) for i in combs[i]]} in fifth degree sum to {int(sums[i]**(1/5))}^5.")   

Integers [27, 84, 110, 133] in fifth degree sum to 144^5.
